name: Elixir CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: url_shortener_dev
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abcd1234
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1.15
      with:
        elixir-version: '1.16'  
        otp-version: '26'      

    - name: Install Dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile

    - name: Create and migrate database
      run: |
        mix ecto.create
        mix ecto.migrate

    - name: Run Tests
      id: tests
      run: mix test
